name: Run tests
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: 'Build, Test, Lint: ${{ matrix.python-version }}'
        uses: chris48s/python-package-shared@main
        with:
          python-version: '3.10'
          pre-install: poetry
